Update README.md
nimeshmora/ecampus-web pull request #19
Opened 2020-11-21 17:45 UTC by sumedhaLakmal

2020-11-21 19:07 UTC, nimeshmora requested changes
this is a markdown file. So, to have your name on a new line in the output,
You have to put 2 or more spaces after your name. Try it.

2020-11-21 19:15 UTC, sumedhaLakmal commented on README.md
> +sumedha Lakmal
sumedha lakmal

2020-11-22 01:32 UTC, nimeshmora commented on README.md
> +sumedha Lakmal
Good work!

2020-11-22 01:32 UTC, nimeshmora approved these changes

2020-11-22 01:32 UTC, merged